name: Benchmark a pull request

on:
  pull_request_target:          # keeps the write token for forked PRs
    branches: [ master ]        # change if your default branch differs

permissions:
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ["1", "1.10"]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run AirspeedVelocity composite action (local path)
        uses: ./                  # uses action.yml at the repo root
        with:
          julia-version: ${{ matrix.julia-version }}
